### ISSUE TITLE
Can't find image asset

### ISSUE THREAD

**Issue by apoleo88** [Nightmare-MY/shortcut#3]
`W/System.err(14930): java.io.FileNotFoundException: flutter_assets/assets/images/logo.png`

My asset are declared in `pubspec.yaml`
I tried with and without the 'assets/' in the URL.

Does it work with flutter assets or does it only accept images in the android res folder?
Which formats does it accept?

Thanks

**Comment by Laurie-Lin** [comment]
which flutter version?this plugin can use flutter assets if it work.

**Comment by apoleo88** [comment]
```
Flutter 2.10.4 • channel stable
Tools • Dart 2.16.2 • DevTools 2.9.2
```

pubspec.yaml:
```
assets:
    - images/
```

**Comment by apoleo88** [comment]
Are you sure it is searching in the flutter app assets and not in the plugin assets folder?

**Comment by Laurie-Lin** [comment]
Well, this plugin hasn't been maintained in a while,In previous tests,reading flutter resources did work

you can read the native code,https://github.com/nightmare-space/shortcut/blob/2cc52d03896f82233d6761fc9abd1d2ae1db6868/android/src/main/java/com/nightmare/shortcut/ShortcutPlugin.java#L74

**Comment by apoleo88** [comment]
So it only accepts bitmaps?

**Comment by Laurie-Lin** [comment]
Please submit a demo that can reproduce the bug to me.
now i still have no idea with your problem.

**Comment by apoleo88** [comment]
There is not much to add, is the example you provided.
But it doesn't find the image, that is why I asked you if it can only read **bitmaps**, I used a png.

```
    Shortcut.addShortcut(
      assetName: 'assets/images/logo.png',
      name: 'Hello',
      packageName: 'app.myapp
      activityName: 'app.myapp.MainActivity',
      intentExtra: {
        'route': '/rom',
      },
    );
```
```

W/System.err(30037): java.io.FileNotFoundException: flutter_assets/assets/images/logo.png
W/System.err(30037): 	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
W/System.err(30037): 	at android.content.res.AssetManager.open(AssetManager.java:881)
W/System.err(30037): 	at android.content.res.AssetManager.open(AssetManager.java:858)
W/System.err(30037): 	at com.nightmare.shortcut.ShortcutPlugin.getImageFromAssetsFile(ShortcutPlugin.java:77)
W/System.err(30037): 	at com.nightmare.shortcut.ShortcutPlugin.onMethodCall(ShortcutPlugin.java:64)
W/System.err(30037): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
W/System.err(30037): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
W/System.err(30037): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
W/System.err(30037): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$AIEPqY6mWzaNK15HekX9bftoAXs.run(Unknown Source:12)
W/System.err(30037): 	at android.os.Handler.handleCallback(Handler.java:938)
W/System.err(30037): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(30037): 	at android.os.Looper.loopOnce(Looper.java:201)
W/System.err(30037): 	at android.os.Looper.loop(Looper.java:288)
W/System.err(30037): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
W/System.err(30037): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(30037): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
W/System.err(30037): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/MethodChannel#shortcut(30037): Failed to handle method call
E/MethodChannel#shortcut(30037): java.lang.IllegalArgumentException: Bitmap must not be null.
E/MethodChannel#shortcut(30037): 	at android.graphics.drawable.Icon.createWithBitmap(Icon.java:651)
E/MethodChannel#shortcut(30037): 	at com.nightmare.shortcut.ShortcutPlugin.addShortcut(ShortcutPlugin.java:126)
E/MethodChannel#shortcut(30037): 	at com.nightmare.shortcut.ShortcutPlugin.onMethodCall(ShortcutPlugin.java:64)
E/MethodChannel#shortcut(30037): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#shortcut(30037): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/MethodChannel#shortcut(30037): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/MethodChannel#shortcut(30037): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$AIEPqY6mWzaNK15HekX9bftoAXs.run(Unknown Source:12)
E/MethodChannel#shortcut(30037): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#shortcut(30037): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#shortcut(30037): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#shortcut(30037): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#shortcut(30037): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/MethodChannel#shortcut(30037): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#shortcut(30037): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#shortcut(30037): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```

**Comment by Laurie-Lin** [comment]
Please provide the YAML configuration file in flutter project,The error log appears to be caused by a file not found，not dont`t support png,i need know your project assets structure and yaml file
